openapi: 3.0.0
info:
  title: ms-products
  description: Descrição da API
  version: 1.0.0
paths:
  /products:
    get: # O método HTTP para este endpoint
      summary: Return all products
      description: Product List - This endpoint returns all products
      responses:
        200:
          description: Sucess response
        404:
          description: Nenhum produto encontrado.
        500:
          description: Ocorreu um erro inesperado
  /products/{productId}:
    get:  # O método HTTP para este endpoint
      summary: Buscar produto por ID
      description: Este endpoint retorna detalhes de um produto com base no ID fornecido.
      responses:
        200:
          description: Resposta bem-sucedida
        404:
          description: Produto não encontrado com o ID especificado
        500:
          description: Ocorreu um erro inesperado.
  /products/{id}:
    put:
      summary: Update product by id
      description: Update products  - this endpoint update products in database
      parameters:
        - name: id
          in: query
          description: product id is needed for finding in database
          required: true
          schema:
            type: long
      responses:
        201:
          description: success updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: long
                  name:
                    type: string
                  description:
                    type: string
                  value:
                    type: double
        404:
          description: product id not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  status:
                    type: string
                  message:
                    type: string
        400:
          description: invalid data sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  status:
                    type: string
                  message:
                    type: string
        500:
          description: occurred an unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  status:
                    type: string
                  message:
                    type: string