openapi: 3.0.0
info:
  title: ms-orders
  description: Descrição da API
  version: 1.0.0
paths:
  /orders/{id}:
    get:
      summary: Get an order by ID
      description: Retrieves an order by its unique ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Order ID to get.
      responses:
        '200':
          description: Operation carried out successfully
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid order ID.
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                type: object
