openapi: 3.0.0
info:
  title: ms-feedback
  description: Descrição da API
  version: 1.0.0
paths:
  /feedbacks:
    post:
      summary: create feedbacks
      description: create feedbacks if order id exists in database and order isn't canceled
      responses:
        201:
          description: feedback created
          content:
            application/json:
              schema:
                type: object
        400:
          description: order canceled status
          content:
            application/json:
              schema:
                type: object
        404:
          description: order_id doesn't exists
          content:
            application/json:
              schema:
                type: object
        500:
          description: any other error
          content:
            application/json:
              schema:
                type: object
