openapi: 3.0.0
info:
  title: ms-feedback
  description: Descrição da API
  version: 1.0.0
paths:
  /feedbacks/{id}:
    get:
      summary: Get an feedback by ID
      description: Retrieves an feedback by its unique ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Feedback ID to get.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Feedback not found
          content:
            application/json:
              schema:
                type: object
  /feedbacks:
    post:
      summary: create feedbacks
      description: create feedbacks if order id exists in database and order isn't canceled
      responses:
        201:
          description: feedback created
          content:
            application/json:
              schema:
                type: object
        400:
          description: order canceled status
          content:
            application/json:
              schema:
                type: object
        404:
          description: order_id doesn't exists
          content:
            application/json:
              schema:
                type: object
        500:
          description: any other error
          content:
            application/json:
              schema:
                type: object
