INSERT INTO `products_tb` (`name`,`description`,`price`) VALUES ('camo t-shirt', 'long camo t-shirt', 13.90),
                                                                ('camo hat', 'camo war hat', 60.50),
                                                                ('blazer gucci', 'very expansive blazer', 2500.90),
                                                                ('pants green', 'sdfsdfsdfdsfsdfsdfsdf', 13.90),
                                                                ('rainbow t-shirt', 'rainbow galasssdsdfdf', 25.90),
                                                                ('gold clock', 'griff clockdfsdfsdf', 3000),
                                                                ('jeans pants standard', 'standard pants', 70.90),
                                                                ('jeans t-shirt', 'jeans t-shirt very very cool', 50.90),
                                                                ('jacket leather', 'jacket leather very cool ', 190.90),
                                                                ('boot leather', 'boot very cool', 200.90)